const lunch = [{
    id: 1,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/05/Skinny_Taste_Greek_Cottage_cheese_bowl-3.jpg",
    name: "Greek Cottage Cheese Bowl",
    description: "Need a quick lunch that doesn’t require cooking or reheating? Then you’ll love this recipe! I created this savory cottage cheese bowl inspired by a Greek salad with tomatoes, cucumbers, bell pepper, kalamata olives, feta, and fresh dill. I’ll be making this cottage cheese lunch bowl all summer, it couldn’t be simpler. Just chop the veggies and combine everything in a bowl. It’s fast, delicious, and packed with protein. More savory cottage cheese bowl recipes you may like are this Burst Tomato Cottage Cheese Caprese Bowl and Savory Cottage Cheese Bowl. And if you prefer a sweeter bowl, try this Berry Cottage Cheese Breakfast Bowl.",
    ingredients: "Cottage Cheese: I used Good Culture’s 2% cottage cheese. It’s my favorite brand, but any will work. | Dill: Chop a tablespoon of fresh dill. | Vegetables: Cherry tomatoes, yellow or orange bell pepper, mini cucumbers | Salt and Pepper to season the veggies | Olives: Chop pitted Kalamata olives. | Feta crumbled on top | Olive Oil for drizzling if desired",
    directions: "Mix the cottage cheese and half of the dill in a small bowl. | Add the veggies and season with salt and pepper. | Top with olives, feta, and remaining dill, and drizzle with olive oil.",
    variations: "Not a cottage cheese fan? If you don’t like the texture, puree the cottage cheese until smooth, or substitute it with Greek yogurt. | Tomatoes: Swap cherry with grape tomatoes, or seed and dice a vine- ripened tomato. | Cucumbers: Substitute an English cucumber. If you use a regular one, peel and seed it before dicing. | Vegetables: Add shallots, green onions, radishes, or beets. | Nuts: Top with pine nuts, almonds, or pistachios. | Seasoning: Sprinkle with everything bagel seasoning, onion powder, or garlic powder. | Briny Flavor: Add capers or artichoke hearts. | Herbs: Top with fresh parsley, basil, or mint. | Serving Suggestion: Dip pita bread or chips in this Greek cottage cheese bowl.",
    course: "Lunch",
    review: "2.5k",
    category: "non-veg",
    timeRequired: "15 mins",
}, {
    id: 2,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/03/Italian-Sub-Broccoli-Spoon-Salad-5.jpg",
    name: "Italian Sub Broccoli Salad",
    description: "I posted this classic broccoli salad a few weeks ago. This new salad is inspired by an Italian Hero sandwich, turned salad. The bold flavors of an Italian sub come to life in this chopped Italian Broccoli Salad, thanks to broccoli, whose mild flavor doesn’t compete. This adaptable chopped salad packs tons of texture and flavor by combining finely chopped raw broccoli, chickpeas, tomatoes, pepperoncini, mozzarella, provolone, salami, ham, and turkey. It’s all tossed in a red wine vinaigrette that soaks into the florets, only",
    ingredients: "Red Onion: Thinly slice half a small red onion. | Broccoli: You’ll need eight cups of broccoli florets from about a pound of broccoli. | Cherry Tomatoes: Quarter one cup of tomatoes. Grape tomatoes would also work. | Chickpeas: Drain and rinse a can of chickpeas. | Mozzarella: Use fresh mozzarella, not pre-shredded. | Meat: Diced genoa salami, lean deli ham, deli turkey. | Pepperoncini: Slice pepperoncini and use two tablespoons of brine. | Broccoli Salad Italian Dressing: Olive oil, red wine vinegar, kosher salt, freshly ground black pepper, dried oregano.",
    directions: "Vinaigrette: Combine the onions, a quarter cup of olive oil, red wine vinegar, salt, oregano, and black pepper in a large bowl. Add the chickpeas, and let the mixture marinate while you prepare the other ingredients. | Salad: Add the meat, veggies, cheese, pepperoncini, and brine to the dressing, and stir in the remaining oil",
    variations: "Olives: Add some sliced black olives | Heat: Mix in some pickled jalapenos for spice. | More Veggies: Add diced cucumbers, carrots, or roasted red peppers. | Swap salami for soppressata or prosciutto. | Swap ham for capicola. | Lean Meat: Use extra turkey breast and less of the other meats for more lean protein. | Vegetarian Broccoli Salad: Omit the meat and add more vegetables. | Vinegar: If you like your Italian sub extra juicy, serve the salad with more red wine vinegar at the table.",
    course: "Lunch",
    review: "2.4k",
    category: "veg",
    timeRequired: "15 mins",
}, {
    id: 3,
    image: "https://www.skinnytaste.com/wp-content/uploads/2021/08/Cilantro-Lime-Chicken-Breast-5.jpg",
    name: "Cilantro Lime Chicken Breast (Grilled or Air Fryer)",
    description: "Switch up your grilled chicken game with cilantro and lime. Chicken breasts can be a little boring, but this marinade makes them a lot more exciting. Of course, chicken thighs would work great here too. You can cook the chicken however you prefer – on the grill, grill pan, or air fryer – and add it to bowls, salads, or tacos. For more ways I use this classic flavor combo, try my Cilantro Lime Rice, Cilantro Lime Fish Tacos, and Cilantro Lime Shrimp.",
    ingredients: "",
    directions: "Grill: Heat a grill or grill pan over medium to medium-high heat and cook the chicken for five minutes on each side. To ensure they’re cooked through, use a meat thermometer to check that the internal temperate is 165 degrees. | Air Fryer: Cook the chicken in the air fryer at 380 degrees for five minutes on each side.",
    variations: "Sub chicken thighs. | Use this marinade as a base and change up the flavors with different citrus and herbs, like lemon and basil or orange and rosemary.",
    course: "Lunch",
    review: "3.5k",
    category: "non-veg",
    timeRequired: "1 hr 20 mins",
}, {
    id: 4,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/06/turkey-burgers-2.jpg",
    name: "Turkey Burger Recipe",
    description: "I wanted to create a basic turkey burger you can eat on a bun, just like a beef burger. Something with no added veggies, like my Turkey Zucchini Burgers or Turkey Broccoli Rabe Burgers, which are delicious too. I’ve purchased turkey burgers, like Bubba Burgers, from the supermarket, and I think they’re awful. This turkey burger recipe is delicious, perfect for a quick dinner or a casual weekend get-together. It’s versatile and made with condiments you already have in your kitchen. Feel free to get creative with your toppings or mix in different herbs and spices to the ground turkey mixture to make it your own!",
    ingredients: "Ground Turkey: Choose 93% lean ground turkey. 99% ground turkey meat would be too dry. If you prefer a beef burger, substitute 90% lean ground beef. | Breadcrumbs: Use seasoned whole wheat or gluten-free breadcrumbs to keep the turkey together. How do you add flavor to ground turkey? Dried onion flakes, ketchup, Worcestershire sauce, grated garlic, and salt flavor turkey burgers. | Burger Buns: I prefer whole-wheat buns often use Martin’s whole wheat potato rolls or Old Tyme’s 647 rolls for fewer carbs and calories and more fiber. | Popular Burger Toppings: Cheese, tomato, red onion, iceberg lettuce, sliced pickles, ketchup, mustard, caramelized onions, and avocado are all great options.",
    directions: "Make the Patties: Combine ground turkey, breadcrumbs, dried onion flakes, ketchup, Worcestershire, garlic, and salt. Divide the meat mixture into four equal portions and press down into half-inch thick patties. | Cook on the Stove: Heat a large nonstick skillet on medium-low heat. When hot, lightly spray it with oil, add the burgers, and reduce the heat to low. Cook for four to five minutes on each side until browned and cooked through (the internal temperature should be 165°F). | Air Fryer: Air fry turkey burgers 400F about 4 to 5 minutes on each side. | Grill Turkey Burgers: Clean the grill well and wipe the grates with a paper towel covered in oil to prevent sticking. Cook the burgers on medium heat for about 5 minutes on each side. | Assemble the Burgers: While the patties cook, toast the buns, and prepare your toppings. Place the meat on the bread and top with your veggies and condiments.",
    variations: "Preheat the Grill: Ensure your grill is hot before you put the burgers on. A hot grill helps sear the meat quickly, keeping the juices in and preventing sticking. | Oil the Grill Grates: Before you start grilling, rub a paper towel soaked in vegetable oil over the grates, which will create a nonstick surface. | Don’t Move the Burgers Too Soon: After placing your burgers on the grill, let them cook undisturbed until they release easily, typically about five to six minutes. If you flip them too soon, they may stick. | Use a Spatula: When it’s time to flip your burgers, use a wide spatula and scoop under the meat completely to prevent them from falling apart.",
    course: "Lunch",
    review: "3.6",
    category: "veg",
    timeRequired: "25 mins",
}, {
    id: 5,
    image: "https://www.skinnytaste.com/wp-content/uploads/2008/07/Classic-Chicken-Salad-4.jpg",
    name: "Classic Chicken Salad Recipe",
    description: "This traditional Chicken Salad recipe, made with simple ingredients is perfect for make-ahead lunches. There’s so many ways to eat it, like as a chicken salad sandwich, on a bagel, over a salad or in lettuce wraps. It’s is my go-to lunch to keep on hand in the refrigerator to eat throughout the week, or to bring to potlucks and it’s dairy-free, gluten-free, high protein, and low-carb. Some more of my favorite healthy chicken salad recipes are Cilantro Chicken Salad, Ranch Chicken Salad, and Chicken Salad with Lemon and Dill. You may also enjoy my classic Egg Salad.",
    ingredients: "Chicken: Chop 12 ounces of cooked chicken breasts from 1 whole roasted chicken. You can also use rotisserie chicken to save time. Mayonnaise: I use light mayo to reduce the calories, but feel free to use your favorite mayo. | Celery: Chop celery for some crunch and veggies. | Red Onion: Swap red onion for scallions or chives. | Chicken Broth: If the chicken salad is a little dry, stir in two tablespoons of broth. | Dijon Mustard for a little tang | Seasoned Salt and Black Pepper for flavor",
    directions: "Cover chicken breast in broth in a small pot, add water if it doesn’t cover the chicken.Add salt and pepper, a piece of celery and it’s leaves (you could add herbs like parsley, garlic, onion, or whatever you want) and bring to a boil. Reduce to a simmer and cook 5 minutes. | Remove from heat, cover tight and let it sit for 15-20 minutes or until thickest part of the breast registers 160 degrees. | Chicken will be cooked through. Let it cool and chop.",
    variations: "Mayo Swap: Substitute Greek yogurt for the mayonnaise or use half yogurt, half mayo. | Add some diced apples or grapes for sweetness and crunch. | You can add nuts like almonds, walnuts or pecans.  | Mix in dried cranberries or cherries for a pop of sweetness. | Add some chopped pickles for a sour bite. | Herbs: Sprinkle in fresh dill, green onions or parsley. | Curry Salad Version: Add some powdered curry seasoning and chopped cilantro, swap the mayo for yougurt. | Chicken Salad Pasta: Mix the chicken salad with some elbow macaroni and a little more mayo to make it a meal. Add more seasoning like everything bagel seasoning, onion powder or garlic powder.",
    course: "Lunch",
    review: "4.6k",
    category: "non-veg",
    timeRequired: "10 mins",
}, {
    id: 6,
    image: "https://www.skinnytaste.com/wp-content/uploads/2010/08/Skinny-Tuna-Melt-7.jpg",
    name: "Open-Faced Tuna Melt Sandwich Recipe",
    description: "Diner comfort food just got a makeover! This classic tuna melt has the perfect amount of crunch, melty cheddar cheese, and veggies. Melts are one of my favorite types of lunch sandwiches. If you love a hot sandwich, you should also try these Open-Faced Turkey Melts and Egg and Tomato Breakfast Melts. If you want a cold sandwich, definitely check out my Open Faced Tuna Sandwich with Avocado.",
    ingredients: "Chicken: Chop 12 ounces of cooked chicken breasts from 1 whole roasted chicken. You can also use rotisserie chicken to save time. Mayonnaise: I use light mayo to reduce the calories, but feel free to use your favorite mayo. | Celery: Chop celery for some crunch and veggies. | Red Onion: Swap red onion for scallions or chives. | Chicken Broth: If the chicken salad is a little dry, stir in two tablespoons of broth. | Dijon Mustard for a little tang | Seasoned Salt and Black Pepper for flavor",
    directions: "Combine tuna, celery, carrots, onion, mayonnaise, vinegar, salt and pepper. | Heat a large skillet over low heat. | Spray skillet with oil, and place two slices of bread on top. | Top bread with cheese, then tuna salad and tomato. Cook on low heat until cheese melts and bread toasty. | Serve immediately.",
    variations: "Swap the whole grain bread for bagels, sourdough, English muffins, or whatever you have on hand. | Use another cheese like Swiss or gouda in place of the cheddar.",
    course: "Lunch",
    review: "3.5k",
    category: "non-veg",
    timeRequired: "10 mins",
}, {
    id: 7,
    image: "https://www.skinnytaste.com/wp-content/uploads/2019/01/egg-salad-5.jpg",
    name: "Classic Egg Salad",
    description: "It’s funny how I have so many variations of egg salad recipes on my site, like this Chickpea Egg Salad and this Avocado Egg Salad, yet don’t have this classic, which I eat all the time. Problem solved! I make a batch of Instant Pot Hard Boiled Eggs and make this on the weekend to have for the week. You can easily double or triple this recipe or make this stove top Hard Boiled Eggs method.",
    ingredients: "6 hard boiled eggs, peeled and chopped | 3 tablespoons mayonnaise | 1 teaspoon finely chopped red onion | 1/8 teaspoon kosher salt | fresh black pepper, to taste | 1/8 teaspoon sweet paprika, for garnish | chopped chives, for garnish",
    directions: "Add pickle juice or diced pickles | Include some veggies like chopped celery or carrots for texture | Add some Dijon mustard | Add some protein such as diced cooked shrimp, it’s delish! | Swap the chives for fresh dill | Try adding a few capers",
    variations: "Olives: Add some sliced black olives | Heat: Mix in some pickled jalapenos for spice. | More Veggies: Add diced cucumbers, carrots, or roasted red peppers. | Swap salami for soppressata or prosciutto. | Swap ham for capicola. | Lean Meat: Use extra turkey breast and less of the other meats for more lean protein. | Vegetarian Broccoli Salad: Omit the meat and add more vegetables. | Vinegar: If you like your Italian sub extra juicy, serve the salad with more red wine vinegar at the table.",
    course: "Lunch",
    review: "3.5k",
    category: "non-veg",
    timeRequired: "25 mins",
}, {
    id: 8,
    image: "https://www.skinnytaste.com/wp-content/uploads/2011/05/BLT-Lettuce-Wraps-1-2.jpg",
    name: "BLT Lettuce Wraps",
    description: "When I’m eating low-carb, I love using lettuce leaves in place of bread for everything from Turkey Taco Lettuce Wraps, Asian Chicken Lettuce Wraps, and even Steak Lettuce Taco Wrap. BLTs are no exception! There is something about the flavor combination of a BLT that invokes childhood memories of sitting around mom’s kitchen table, it’s funny how the flavors of food can trigger a memory. Oh what I would give to be a kid for a day again! Back then mom made it on white bread, but today I enjoy them just as much on a lettuce wrap, same great flavors without the carbs. See all my lettuce wrap recipes here!",
    ingredients: "4 slices center cut bacon, cooked and chopped | 1 medium tomato, diced | 1 tbsp light mayonnaise, or whole30 approved mayo | 3 large iceberg lettuce leaves | fresh cracked pepper | 1 ounce avocado optional, add 1 point",
    directions: "Look for lettuce leaves that are large enough to hold the filling. I like to use iceberg lettuce for larger cups. Romaine lettuce and baby romaine are also great. | The leaves of butter or boston lettuce are smaller, but also wonderful. | If you prefer, you can turn this into a big chopped salad by simply serving this over a bowl over chopped lettuce.",
    variations: "Preheat the Grill: Ensure your grill is hot before you put the burgers on. A hot grill helps sear the meat quickly, keeping the juices in and preventing sticking. | Oil the Grill Grates: Before you start grilling, rub a paper towel soaked in vegetable oil over the grates, which will create a nonstick surface. | Don’t Move the Burgers Too Soon: After placing your burgers on the grill, let them cook undisturbed until they release easily, typically about five to six minutes. If you flip them too soon, they may stick. | Use a Spatula: When it’s time to flip your burgers, use a wide spatula and scoop under the meat completely to prevent them from falling apart.",
    course: "Lunch",
    review: "6.3k",
    category: "veg",
    timeRequired: "10 mins",
}, {
    id: 9,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/06/Chipotle-Chicken-Thighs-5.jpg",
    name: "Chipotle Chicken",
    description: "This Chipotle Chicken recipe is a delightful combination of smoke, spicy and savory flavors. Whether you cook them in a skillet, on a grill or grill pan, or in the air fryer, the result will be juicy and delicious. If you’re craving a homemade version of the popular food chain restaurant, you’ll love this quick recipe that doesn’t require any marinating time. Turn it into a burrito bowl or burrito with my copycat cilantro lime rice, guacamole and pico de gallo. Or use it for taco night, over salad or quesadillas. My family devours them!",
    ingredients: "Chicken: Trim the fat off boneless, skinless chicken thighs. | Garlic: Mince or crush two garlic cloves. | Chipotle in Adobo Sauce: You’ll only need one tablespoon of the sauce. Freeze the rest in an ice cube and then transfer to a zip-locked bag for later use. | Seasoning: Ancho chile powder, ground cumin, dried oregano, salt, pepper",
    directions: "Season Chicken: Season the thighs with salt and pepper on both sides. Combine the garlic, chipotle in adobo sauce, ancho chile powder, cumin, and oregano in a bowl. Rub the spice mixture evenly over the chicken and let them sit for a few minutes. You can cook them right away or refrigerate as long as overnight for more flavor. | Skillet: Preheat a large skillet or griddle over medium-high heat and spray with oil. Cook the thighs for about six minutes on each side. | Grill: Preheat your grill or grill pan to medium-high heat. Grease the grill grates with oil and cook on each side for six to eight minutes. | Air Fryer: Preheat the air fryer to 400°F and cook the chicken for 14 to 15 minutes, flipping halfway through. | How do you know when chicken is done? No matter which method you choose, the chicken is ready whenever it’s browned on the outside, and the internal temperature is 165°F when checked with a meat thermometer. | Serving: Once cooked, transfer the meat to a plate and let it rest for a few minutes before slicing. This step prevents the juices from running out of the chicken.",
    variations: "Chicken: If you prefer white meat, use chicken breasts. | Ancho Chile Powder: If you don’t have ancho, swap it for regular chili powder.",
    course: "Lunch",
    review: "54.2k",
    category: "non-veg",
    timeRequired: "30 mins",
}, {
    id: 10,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/06/Protein-Bagels-4.jpg",
    name: "Protein Bagels with Cottage Cheese",
    description: "Remember my Greek yogurt bagels? They’re so last year! What’s new? Cottage cheese everything and anything! Cottage cheese is trending this year, and I’ve been using it in everything from my cottage cheese scrambled eggs, cottage cheese lasagna roll ups to savory cottage cheese bowls. These protein bagels are made with just 5 ingredients, plus toppings! You can make them in the oven or air fryer (my favorite way!). I basically swapped the yogurt in my bagel recipe for cottage cheese and it’s worked out beautifully. For extra protein, serve this with egg salad, chicken salad or turn it into a bacon egg and cheese breakfast bagel!",
    ingredients: "Flour: This recipe works with unbleached all purpose flour, whole wheat flour or gluten-free flour mix such as Cup4Cup. | Baking Powder: For rising, make sure it’s not expired. | Kosher Salt: Also helps flour rise, I use kosher salt, if you use table salt you make have to cut in half. | Cottage Cheese: Use 1 cup 2% cottage cheese (I like Good Culture) and strain it in a mesh sieve so it’s thick. | Egg: 1 large egg or egg white, beaten (to help the toppings stick) If you can’t eat eggs, you can omit and just press them into the dough. | Optional toppings: If you like a plain bagel, no toppings needed. But if you like seasonings, try this with everything bagel seasoning, sesame seeds, poppy seeds, dried garlic flakes, dried onion flakes, etc.",
    directions: "Combine Dry Ingredients: In a large bowl combine the flour, baking powder and salt and whisk well. | Strain Cottage Cheese so it’s Thick: Add the strained cottage cheese and mix with a fork or spatula until well combined, it will look like small crumbles. If you don’t strain it well, the dough will be sticky. | Knead: Using your clean hands, working in the bowl, knead the dough until it comes together and is smooth, tacky, but not sticky, about 2 minutes (it should not leave dough on your hand when you pull away). | Form Into Bagels: Divide into 4 equal balls. Roll each ball into 3/4-inch thick ropes and join the ends to form bagels. (or you can make a ball and poke a hole in the center then stretch it slightly) | Egg Wash: Brush with egg wash and sprinkle both sides with seasoning of your choice. | Air Fryer Method: Spray air fryer basket with oil. Transfer the bagels to the air fryer basket in batches without overcrowding and air fry 280F 15 to 16 minutes, or until golden. No need to turn. Let cool at least 15 minutes before cutting, this step is a must. | Oven Method: Preheat oven to 375F. Place parchment paper or a silpat on a baking sheet. If using parchment paper, spray with oil to avoid sticking. | Bake on the top rack of the oven for 25 minutes. Let cool at least 15 minutes before cutting, this step is a must.",
    variations: "Sub chicken thighs. | Use this marinade as a base and change up the flavors with different citrus and herbs, like lemon and basil or orange and rosemary.",
    course: "Lunch",
    review: "5.4k",
    category: "veg",
    timeRequired: "37 mins",
}]

export default lunch;
