export const random = [{
    id: 6,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/02/Tropical-Chia-Pudding-Breakfast-Bowl-9.jpg",
    name: "Tropical Chia Pudding Breakfast Bowl",
    description: "This easy, high-protein, Tropical Chia Pudding Breakfast Bowl is creamy and delicious, made with chia seeds, Greek yogurt, mango and kiwi. “Why not add a natural boost from Greek yogurt to my pudding?” The results were delicious! The yogurt supplies a whopping 12 grams of protein per serving and creates a thicker, creamier pudding consistency, providing the perfect base layer for the tropical fruit topping. And toasted coconut is the perfect finale, giving it a little texture and a delicious, nutty flavor. If you want more chia recipes, try my Mango Coconut Chia Pudding or this 15-Minute Protein Chia Seed Cereal.",
    category: "Veg",
    ingredients: "Chia Seeds: You’ll need a quarter cup of chia seeds for the pudding. | Milk: I used unsweetened vanilla almond milk, but any kind will work. Use dairy, oat, hemp, etc. | Yogurt: I used nonfat plain Greek yogurt with probiotics, you can use dairy-free yogurt to make it DF but the protein will be less. | Sweetener: Monk fruit, stevia, maple syrup, or honey will work. | Fruit: Kiwi, mango are used here but papaya or pineapple could also work! | Coconut: Top the bowls with shredded, unsweetened coconut.",
    directions: "Chia Pudding: Whisk chia seeds, almond milk, yogurt, and sweetener in a large container and refrigerate for a minimum of two hours or as long as overnight. | Toasted Coconut: Heat a small skillet on medium-low and toast the coconut for about four minutes until golden brown. | Assemble the Breakfast Bowls: Divide the pudding into two small bowls and top with kiwi, mango, and coconut. Drizzle with a little extra sweetener if desired.",
    variations: "Fruit: Swap mango or kiwi for pineapple, papaya, or cantaloupe to keep it tropical or a mix of fresh berries. | Coconut: You can also toast the coconut in the oven at 325°F for about five to ten minutes. And if all you have is sweetened coconut, it will work. | Milk: Use 2%, oat, or coconut milk if you prefer.",
    course: "Breakfast",
    review: "4.1k"
},
{
    id: 7,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/02/Egg-White-Muffins-with-Turkey-Bacon-Cottage-Cheese-and-Veggies-8-1024x1536.jpg",
    name: "High Protein Egg White Muffins with Turkey Bacon",
    description: "Deviled eggs are perfect if you’re looking for an inexpensive, low-carb appetizer or snack, especially if you need something keto-friendly. This classic deviled egg recipe is one of my favorites, but if you want to try some with a twist, you may also like these Instant Pot Deviled Eggs, which are slightly different, Deviled Guacamole Eggs, and Deviled Tuna Eggs.",
    category: "Non-Veg",
    ingredients: "Egg Whites: Buy a 16-ounce carton of egg whites. | Cottage Cheese: You’ll need one small container of 2% cottage cheese. | Seasoning: Garlic powder, seasoning salt | Onions: Chop shallots (or red onions) and scallions. | Bell Pepper: I like using orange or red bell pepper. | Broccoli: Steam and chop a half cup of fresh or frozen broccoli. | Turkey Bacon: Cut six slices of turkey bacon in half. I used Applegate, but any brand will do. | Cheese: Sharp shredded cheddar cheese",
    directions: "Vegetables: Sauté the shallots, scallions, and bell pepper in olive oil over medium-low heat for about five minutes. Add in the broccoli and cook for a minute. | Egg Mixture: Combine the egg whites, cottage cheese, garlic powder, and seasoning salt, and then mix in the vegetables. | Line a muffin tin with a half slice of turkey bacon around the edges, pour in the eggs, and top the cups with shredded cheese.",
    variations: "Eggs: I used one carton of egg whites. If you prefer yolks, you can use half whole eggs and half whites or all whole eggs. You’ll need about two cups total. | Vegetables: You can substitute the veggies with anything you like. Try it with leftover roasted veggies, mushrooms, spinach, etc. | Cheese: Swap the cheddar with shredded Swiss or mozzarella.",
    course: "Breakfast",
    review: "5k"
},
{
    id: 8,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/02/Egg-White-Muffins-with-Turkey-Bacon-Cottage-Cheese-and-Veggies-8-1024x1536.jpg",
    name: "Savory Steel Cut Oatmeal",
    description: "Meal prep these delicious, high-protein Egg White Muffins with turkey bacon, cottage cheese, and veggies for a quick breakfast on the go!. All oats are nutrition-packed, but steel cut oats are a bit healthier than rolled and quick cooking oats. The difference between the three types is how they’re processed. Since steel cut are the least processed, they also have the highest fiber and protein content and rank the lowest on the glycemic index, meaning they will impact your blood sugar less. They take the longest to cook and are the heartiest oat with a chewier texture compared to the others.",
    category: "Non-Veg",
    ingredients: "Egg Whites: Buy a 16-ounce carton of egg whites. | Cottage Cheese: You’ll need one small container of 2% cottage cheese. | Seasoning: Garlic powder, seasoning salt | Onions: Chop shallots (or red onions) and scallions. | Bell Pepper: I like using orange or red bell pepper. | Broccoli: Steam and chop a half cup of fresh or frozen broccoli. | Turkey Bacon: Cut six slices of turkey bacon in half. I used Applegate, but any brand will do. | Cheese: Sharp shredded cheddar cheese",
    directions: "Vegetables: Sauté the shallots, scallions, and bell pepper in olive oil over medium-low heat for about five minutes. Add in the broccoli and cook for a minute. | Egg Mixture: Combine the egg whites, cottage cheese, garlic powder, and seasoning salt, and then mix in the vegetables. | Line a muffin tin with a half slice of turkey bacon around the edges, pour in the eggs, and top the cups with shredded cheese.",
    variations: "Vegetarian: Omit the sausage | Dairy Free: Omit the parmesan cheese | Egg Free: Omit the egg, there’s still plenty of protein.",
    course: "Breakfast",
    review: "2.9k"
},
{
    id: 9,
    image: "https://www.skinnytaste.com/wp-content/uploads/2022/11/High-Protein-Enchilada-Scramble-3.jpg",
    name: "High-Protein Enchilada Scrambled Eggs",
    description: "This healthy, avocado toast recipe is made on whole grain toast with mashed avocado, and your favorite egg. You can make this with a hard boiled egg, sunny side up, scrambled, or poached. If you’re like me, you make even want to add a few dashes of hot sauce! Adding egg to avocado toast is an easy way to add protein to breakfast toast. If you want a vegan option, you might also like this avocado toast with lemon and kale.",
    category: "Non-Veg",
    ingredients: "Eggs: You can make it with all egg whites or all eggs, but I often do a mix of both. | Adobo Seasoning: For flavor. | Enchilada Sauce: I think the homemade enchilada sauce makes the dish, but if you prefer to use canned, you can, but it just won’t taste as good. | Cheese: I love scrambled eggs with cheese, so I topped them with shredded cheddar. | Vegetables: Top the eggs with chopped scallions and sliced avocado.",
    directions: "Beat the egg and egg whites with adobo seasoning. | Cook: Heat a small skillet over medium-high heat and spray it with oil. Once hot, add the eggs, reduce the heat to medium, and cook for a few minutes. | Top the eggs with enchilada sauce and cheese and cover the skillet. Cook on low until the cheese melts. | Serve: Remove the pan from the heat, and top the scramble with avocado and scallio",
    variations: "Sauce: I’m sure salsa verde would also be delicious on these eggs if you don’t have enchilada sauce. | Cheese: You can also use Monterey Jack or a dairy-free cheddar. | Herbs: Top the eggs with fresh cilantro. | More Servings: Double or triple the recipe to feed more people. | For added carbs, char a tortilla to make a breakfast taco. | Make It a Meal: If you enjoy eggs for lunch or dinner, I would serve this enchilada scramble with rice and beans on the side.",
    course: "Breakfast",
    review: "3k"
},
{
    id: 10,
    image: "https://www.skinnytaste.com/wp-content/uploads/2023/01/Air-Fryer-Breakfast-Banana-Split-5-1024x1536.jpg",
    name: "Air Fryer Breakfast Banana Split",
    description: "With just five ingredients, this delicious Air Fryer Banana Split tastes like you’re having dessert for breakfast. The bananas are baked in the air fryer and topped with yogurt, maple syrup, cinnamon, and pecans. If you want to make this easy banana breakfast for kids, add some sprinkles and a cherry! These Baked Bananas, Banana Foster-Topped French Toast, and Banana Foster Crepes are some more yummy banana recipes to try. And of course if you need more air fryer recipes I have so many recipes to choose from!",
    category: "Veg",
    ingredients: "Banana: This recipe is the perfect way to use up overripe bananas. The riper, the better! | Cinnamon: Sprinkle a little cinnamon on the banana. | Greek Yogurt: I like Fage or Stonyfield Greek yogurt, but any kind will work. You could also use vanilla yogurt and skip the syrup. | Dairy Free: Use your favorite dairy free yogurt like coconut or almond. | Maple Syrup: Swap it with honey or agave. | Pecans: Chop two tablespoons of pecans. You can sub walnuts or almonds or omit them if you’re allergic.",
    directions: "Air Fry the Banana: Slice a ripe banana lengthwise, three-quarters of the way through, and top it with cinnamon. Air fry the banana for five to six minutes at 400°F until soft. | Greek Yogurt Sauce: While the banana cooks, combine a teaspoon of syrup with the yogurt. | Banana Split Toppings: When the banana is ready, top it with yogurt, cinnamon, pecans, and the remaining syrup.",
    variations: "Drizzle the banana with chocolate syrup, almond butter, or peanut butter. | Fruit: Add fresh berries, pomegranate seeds, raisins, dried cranberries, or crushed-up freeze-dried strawberries. | Top your banana split with chocolate chips, granola, coconut chips, or coconut flakes. | Spices: Add a dash of nutmeg or cardamom, or substitute pumpkin pie spice for cinnamon. | Classic Banana Split: Make it dessert with whipped cream, chocolate syrup, sprinkles, and a cherry on top.",
    course: "Breakfast",
    review: "7.2k"
}]